name: Slack Message
description: Send messages to Slack from GitHub Actions.
branding:
  icon: message-square
  color: purple
runs:
  using: node16
  main: ./index.dist.js
inputs:
  text:
    description: Text to send to Slack, in Slack's "mrkdwn" format - required.
    required: true
  color:
    description: The colour of the Slack attachment.
    required: false
  bot-token:
    description: A Slack bot token to send messages with - required if `webhook-url` was not provided.
    required: false
  webhook-url:
    description: A Slack webhook URL to send messages to - required if `bot-token` was not provided.
    required: false
  channel:
    description: The Slack channel - required if `bot-token`, optional with `webhook-url`.
    required: false
  username:
    description: Set the webhook username - only valid if `webhook-url` was provided.
    required: false
  icon-emoji:
    description: Set the webhook icon_emoji - only valid if `webhook-url` was provided.
    required: false
  icon-url:
    description: Set the webhook icon_url - only valid if `webhook-url` was provided.
    required: false
  message-id:
    description: The ID of the existing Slack message to update - only valid if `bot-token` was provided.
    required: false
  image-url:
    description: Image URL for attachment
    required: false
  thumb-url:
    description: Thumb URL for attachment
    required: false
outputs:
  message-id:
    description: The unique identifier of the Slack message sent.
