name: Test
on:
  # On new pushes to the generated files
  push:
    paths:
      - index.dist.js
  # Upon manual request
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL: G019R925BQA
      SHOW_DEBUG: true
      THROW_ERR: true
    steps:
      - uses: actions/checkout@v4

      - name: someimportantcompany/github-actions-slack-message@master
        uses: ./
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: Firing a bot-token message

      - name: someimportantcompany/github-actions-slack-message@master
        uses: ./
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: Firing a webhook message

      - run: sleep 3s

      - name: someimportantcompany/github-actions-slack-message@master
        uses: ./
        id: slack
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: Deployment started
          color: grey

      - run: sleep 5s

      - name: someimportantcompany/github-actions-slack-message@master
        uses: ./
        with:
          channel: ${{ env.SLACK_CHANNEL }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: Deployment finished
          color: '#28a745'
          message-id: ${{ steps.slack.outputs.message-id }}
